// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hoaimaqlrorzwkxhxrir.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhvYWltYXFscm9yendreGh4cmlyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU2NTE2MTQsImV4cCI6MjA2MTIyNzYxNH0._HfxfKA5xoov-4hvAwy3A2fPX3vdb0rOTDxNErcJ22w";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);